version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    target-branch: main
    open-pull-requests-limit: 5
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 5
    target-branch: main
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
      include: scope
